import {
  REPORTS,
  BROCHURES,
  DIGITAL_CONTENT,
  HEALTH, NEWSLETTERS, NEWS_RELEASE, PODCASTS, PRESENTATIONS, SPOKESMAN, TECHNOLOGY,
} from '../constants';

export default [
  {
    title: 'VMware Win Story: Eskom Data Center Solutions',
    source: 'VMware Win Story: Eskom Data Center Solutions',
    link: 'https://drive.google.com/file/d/1_cKjEtAipyGcO5wxdFOfWurqLHDUOhVx/view?usp=sharing',
    highlight: 'To help Eskom gather the necessary data about the human capital investments that would be most conducive to high performance, executives teamed with Accenture to implement the Accenture Human Capital Development Framework.',
    preview: 'Eskom, the South African Government\'s electrical utility, is in the process of evolving from an environment characterized by central government planning to one marked by more competition and expansion.',
    publicationDate: '',
    publicationLogo: null,
    categories: [TECHNOLOGY, REPORTS],
  },
  {
    title: 'VMware Win Story: Medco Health Solutions',
    source: 'VMware Win Story: Medco Health Solutions',
    link: 'https://drive.google.com/file/d/1llKTK5OWkyZiFu1KFkTGiDpl8G8Z2e4D/view?usp=sharing',
    highlight: '[An] innovative VMware product and Alliance Partner EMC’s solid track record allowed a potential customer, Medco, to identify a strong working relationship that could help them meet their business challenges.',
    preview: 'As one of the nation\'s leading healthcare companies, Medco Health Solutions is facing the challenge of maintaining business agility in a volatile environment with the help of VMware and Alliance Partner EMC, a global leader in IT transformation. The VMware – EMC partnership resulted in the sale of VFabric Gemfire Professional services to Medco.',
    publicationDate: '',
    publicationLogo: null,
    categories: [TECHNOLOGY, REPORTS],
  },
  {
    title: 'Texas\' Medicaid waiver is a \'canary in the coal mine\' for abortion carve-outs',
    source: 'Modern Healthcare',
    link: 'https://www.modernhealthcare.com/article/20170516/NEWS/170519885/texas-medicaid-waiver-is-a-canary-in-the-coal-mine-for-abortion-carve-outs',
    highlight: '"Receipt of the federal funds, in a tough budget year, will help offset the need for devastating cuts to Medicaid eligibility for a pregnant women and/or Medicaid payments to physicians," said Marcus Cooper a spokesman for the Texas Medical Association.',
    preview: 'The Trump administration will soon review Texas\' proposed plan to regain federal funding for its family planning program that does not include Planned Parenthood or providers that support or perform abortions. If the CMS approves the waiver, other states could seek similar permissions and risk millions losing access to care.',
    publicationDate: 'May 16, 2017',
    publicationLogo: null,
    categories: [HEALTH, SPOKESMAN],
  },
  {
    title: 'Family planning available to thousands more in Williamson County',
    source: 'Austin American Statesman',
    link: 'https://www.statesman.com/NEWS/20140108/Family-planning-available-to-thousands-more-in-Williamson-County',
    highlight: 'The Williamson County and Cities Health District is continuing to expand same-day and walk-in appointments for family planning services including pregnancy counseling, pregnancy testing and sexually transmitted disease and urinary infection medication, spokesman Marcus Cooper said.',
    preview: 'Safety net clinics in Williamson County will provide family planning services to thousands more low-income women this year with the help of new government funding.',
    publicationDate: 'Jan 8, 2014',
    publicationLogo: null,
    categories: [HEALTH, SPOKESMAN],
  },
  {
    title: 'Texas leads nation in West Nile cases, and count expected to rise, officials say',
    source: 'Austin American Statesman',
    link: 'https://www.statesman.com/article/20120922/NEWS/309227875',
    highlight: 'The Williamson County &amp; Cities Health District has reported six human cases, including one death. It is looking into ground and aerial spraying of mosquitoes, but no decisions have been made, spokesman Marcus Cooper said.',
    preview: 'Texas is grappling with more than half of the nation’s West Nile virus cases this year, and health officials said Wednesday that they expect the outbreak to worsen in Texas and across the U.S.',
    publicationDate: 'Sep 22, 2012',
    publicationLogo: null,
    categories: [HEALTH, SPOKESMAN],
  },
  {
    title: 'Web Search Is the New King of Government Portals',
    source: 'Government Technology',
    link: 'https://www.govtech.com/archive/web-search-is-the-new-king.html',
    highlight: '"We redesigned and revamped the state Web portal and introduced it in June," Cooper said. "And I think it speaks directly to the survey and what our citizens wanted in a revised website."',
    preview: 'When governments began launching their own websites in the \'90s, the results left much to be desired, to say the least. The portals were painfully difficult to navigate and had multiple tabs that were too busy -- seemingly created with government users in mind rather than the general public.',
    publicationDate: 'Aug 12, 2010',
    publicationLogo: null,
    categories: [TECHNOLOGY, SPOKESMAN],
  },
  {
    title: 'NIC INC : New Texas.gov/voting Web Page Prepares Texans for General Election',
    source: 'www.marketscreener.com',
    link: 'https://www.marketscreener.com/quote/stock/NIC-INC-9154/news/NIC-INC-nbsp-New-Texas-gov-voting-Web-Page-Prepares-Texans-for-General-Election-13455436/',
    highlight: 'Texas.gov helps state and local government entities Web-enable their services and is operated without tax funds through a public-private partnership between the state and Texas NICUSA, LLC.',
    preview: 'Today, Texas.gov, the official website of the State of Texas, introduces www.texas.gov/voting, a webpage dedicated to helping Texans find voting and polling place information. With the Oct. 4 voter registration deadline quickly approaching, Texas.gov provides Texans with easy access to voting information and services, as well as answers to the most commonly asked voting questions in Texas. Via the new webpage, citizens can:',
    publicationDate: 'Sep 13, 2010',
    publicationLogo: null,
    categories: [TECHNOLOGY, NEWS_RELEASE],
  },
  {
    title: 'NIC INC : Get Ready for Back to School Season with Texas.gov',
    source: 'www.marketscreener.com',
    link: 'https://www.marketscreener.com/quote/stock/NIC-INC-9154/news/NIC-INC-nbsp-Get-Ready-for-Back-to-School-Season-with-Texas-gov-13433465/',
    highlight: 'Texas.gov offers an easy, convenient, and cost-effective way for Texans to access services and conduct business with state and local governments as well as higher education institutions across Texas.',
    preview: 'Texas.gov, the official website of the State of Texas, offers many services to help students and their parents get ready to go back to school. Every day, thousands of people visit Texas.gov to search for information, perform online transactions, and securely process payments with 24/7 customer service.',
    publicationDate: 'Aug 5, 2010',
    publicationLogo: null,
    categories: [TECHNOLOGY, NEWS_RELEASE],
  },
  {
    title: 'Crane Collapses in Texas; 1 Dead',
    source: 'Fox News',
    link: 'https://www.foxnews.com/story/crane-collapses-in-texas-1-dead',
    highlight: 'The crane\'s base was in the riverbed when it was attempting to remove the beam, or girder, from the old bridge, Department of Transportation spokesman Marcus Cooper said',
    preview: 'SMITHVILLE, Texas – A crane removing steel beams from an old bridge over the Colorado River became overloaded and toppled Wednesday, killing one worker and injuring another, officials said.',
    publicationDate: 'Jan 13, 2015',
    publicationLogo: null,
    categories: [SPOKESMAN],
  },
  {
    title: 'A Letter from TxDOT',
    source: 'The Pemberton Journal (Neighborhood Newsletter)',
    link: 'http://5f8c274712c4ea693cc1-fdbcf82d3dfc08785157cf0d6fc8ed50.r16.cf1.rackcdn.com/0911PH.pdf',
    highlight: 'This project will bring new road surfaces to your neighborhood that will last several more years.  We hope that is worth the effort.',
    preview: '',
    publicationDate: 'Nov, 2009',
    publicationLogo: null,
    categories: [SPOKESMAN],
  },
  {
    title: 'Texas Physicians Urge Spring Break Safety Precautions',
    source: 'Texas Medical Association News Release',
    link: 'https://drive.google.com/file/d/1FIq2m4dqcvYBwU4kfzCOTIY8o6PXgd77/view?usp=sharing',
    highlight: 'A spring break vacation might sound like a great idea after a year of pandemic-related stress, isolation, and social distancing, but Texas physicians say now is not the time to let our guard down.',
    preview: '',
    publicationDate: 'Mar 16, 2021',
    publicationLogo: null,
    categories: [NEWS_RELEASE, HEALTH],
  },
  {
    title: 'TMA COVID-19 Experts Urge Testing for Schoolchildren',
    source: 'Texas Medical Association News Release',
    link: 'https://drive.google.com/file/d/15V1IBKbSZbDW0OuQ_yfJ2hzuczuGwph0/view?usp=sharing',
    highlight: 'Texas physicians recommend schools use rapid antigen testing along with other on-campus safety measures to detect early signs of coronavirus infection among students and staff.',
    preview: '',
    publicationDate: 'Dec 1, 2020',
    publicationLogo: null,
    categories: [NEWS_RELEASE, HEALTH],
  },
  {
    title: 'Williamson County and Cities Health District Observes National Infant Immunization Week',
    source: 'Williamson County and Cities Health District News Release',
    link: 'https://drive.google.com/file/d/1gbldfrH-DiuODWeykX-AnY1bEUK8z_zK/view?usp=sharing',
    highlight: 'During the week of April 18 – April 25, 2015, the Williamson County and Cities Health District will observe National Infant Immunization Week (NIIW), an annual observance to highlight the importance of protecting infants from vaccine-preventable diseases and celebrate the achievements of immunization programs and their partners in promoting healthy communities.',
    preview: '',
    publicationDate: 'Apr 16, 2015',
    publicationLogo: null,
    categories: [NEWS_RELEASE, HEALTH],
  },
  {
    title: 'Texas Honors Veterans with New, Improved Website: The Texas Veterans Portal',
    source: 'Texas Department of Information Resources News Release',
    link: 'https://drive.google.com/file/d/1QfiG-GJJfXqupzsuYy0WvgEihxdvheHP/view?usp=sharing',
    highlight: 'AUSTIN, Texas – November 9, 2010 – Texas.gov  and the Texas Veterans Commission are proud to announce the launch of a new, improved website for Texas veterans, the Texas Veterans Portal, located atwww.texas.gov/veterans.',
    preview: '',
    publicationDate: 'Nov 9, 2010',
    publicationLogo: null,
    categories: [NEWS_RELEASE, HEALTH],
  },
  {
    title: 'Wilco Wellness Alliance Quarterly | Summer 2012',
    source: 'Wilco Wellness Alliance Quarterly | Summer 2012',
    link: 'https://drive.google.com/file/d/1rj3rX2QiqmzvCP6bxu7nMXaY_nV94VhI/view?usp=sharing',
    highlight: 'This fall, the Alliance will reintroduce the Por Vida initiative to Williamson County diners with a three month marketing campaign beginning in October. The Por Vida program is a partnership between the Alliance and local restaurants to identify the most nutritious items on their menus.',
    preview: '',
    publicationDate: 'Summer 2012',
    publicationLogo: null,
    categories: [NEWSLETTERS],
  },
  {
    title: 'Wilco Wellness Alliance Quarterly | Fall 2012',
    source: 'Wilco Wellness Alliance Quarterly | Fall 2012',
    link: 'https://drive.google.com/file/d/1pMS1yHVg_kKTjEghhLXtJdxfpm43k9uK/view?usp=sharing',
    highlight: 'Over the last three months, the WilCo Wellness Alliance (WWA) has formed several working groups that address each of the Alliance’s initiatives on Chronic Disease, Nutrition, Physical Activity, and Tobacco Use.',
    preview: '',
    publicationDate: 'Fall 2012',
    publicationLogo: null,
    categories: [NEWSLETTERS],
  },
  {
    title: 'Wilco Wellness Alliance Quarterly | Fall 2013',
    source: 'Wilco Wellness Alliance Quarterly | Fall 2013',
    link: 'https://drive.google.com/file/d/1-1mh7NGg42mKo7s6MUYU5Szh2OxDBM5t/view?usp=sharing',
    highlight: 'I think the WilCo Wellness Alliance in building trails, planning community events, and making sure people have access to health care....-those kinds of things are just going to become more important as the population expands.',
    preview: '',
    publicationDate: 'Fall 2013',
    publicationLogo: null,
    categories: [NEWSLETTERS],
  },
  {
    title: 'Wilco Wellness Alliance Quarterly | Fall 2014',
    source: 'Wilco Wellness Alliance Quarterly | Fall 2014',
    link: 'https://drive.google.com/file/d/1HP9Z_ouaGQpv_78eM8mudzhJ2jXX9eov/view?usp=sharing',
    highlight: 'The WilCo Wellness Alliance and the Williamson County Mental Health Task Force recently joined together to collaborate and enhance the current mission of both groups. The Mental Health Taskforce was established in 2003 and currently focuses on mental health and behavioral health among both adult and youth populations through the general Mental Health Task Force and the Children and Youth Behavioral Health Subcommittee.',
    preview: '',
    publicationDate: 'Fall 2014',
    publicationLogo: null,
    categories: [NEWSLETTERS],
  },
  {
    title: 'TMA Legislative News Hotline Podcast Sea. 2 Ep. 3',
    source: 'Podcast',
    link: 'https://anchor.fm/marcus-cooper1/episodes/TMA-Legislative-News-Hotline-Podcast-Sea--2-Ep--3-evnr5j',
    highlight: 'TMA\'s Multimedia Manager Marcus Cooper examines the Texas Legislative budget and it\'s impact on Texas medicine and public health.',
    preview: '',
    publicationDate: 'Apr 26',
    publicationLogo: null,
    categories: [PODCASTS],
  },
  {
    title: 'Know Your Risk During COVID-19',
    source: 'TMA COVID-19 Risk Assessment Chart',
    link: 'https://drive.google.com/file/d/1sG660nThgVKqQ-DVUdM0RQxoeI4a0zRV/view?usp=sharing',
    highlight: 'BE INFORMED: Know Your Risk During COVID-19',
    preview: '',
    publicationDate: '2020',
    publicationLogo: null,
    categories: [DIGITAL_CONTENT, HEALTH],
  },
  {
    title: 'WCCHD Board Report',
    source: 'WCCHD Board Report',
    link: 'https://drive.google.com/file/d/19qIxok7v6JxFQIKGL4B6D-VYnyiUJJu9/view?usp=sharing',
    highlight: 'The 10 Essential Public Health Services describe the public health activities that all communities should undertake and serve as the framework for the National Public Health Performance Standards. Public health systems should:',
    preview: '',
    publicationDate: 'Jan 2015',
    publicationLogo: null,
    categories: [DIGITAL_CONTENT, REPORTS, HEALTH],
  },
  {
    title: 'Yes, I’m Ready to Quit',
    source: 'Texas Department of Health Tobacco Prevention Brochure',
    link: 'https://drive.google.com/file/d/1Pe9EF8Oct9hFtBnlYCq6WS4H4QOaunpl/view?usp=sharing',
    highlight: 'This brief guide can launch you into your new life free of cigarettes, but you need to drive the plan and rally the support. No two smokers are alike, and your quit-smoking plan with its unique support measures will reflect your life, needs and concerns. Quitting isn’t easy, but more than 3 million people find a way to quit each year. Now, you can join them.',
    preview: '',
    publicationDate: '',
    publicationLogo: null,
    categories: [DIGITAL_CONTENT, BROCHURES, HEALTH],
  },
  {
    title: 'A Clinical Toolkit for Treating Tobacco Dependence',
    source: 'Powerpoint Presentation',
    link: 'https://drive.google.com/file/d/1-MjFmqvenYlPtOIdLpdLKMVFYRQvP3em/view?usp=sharing',
    highlight: 'The Clinical Toolkit can be used with teens, pregnant women and adult populations.',
    preview: 'PowerPoint Presentation',
    publicationDate: '',
    publicationLogo: null,
    categories: [PRESENTATIONS, HEALTH],
  },
];
